org: maeoka
app: infobot
service: infobot-slack
frameworkVersion: '2'
useDotenv: true
# AWS
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: eu-west-2
  environment:
    SLACK_SIGNING_SECRET: ${env:KEY_1}
    SLACK_BOT_TOKEN: ${env:KEY_3}
    SLACK_APP_TOKEN: ${env:KEY_5}
    SLACK_CLIENT_ID:  ${env:KEY_6}
    SLACK_CLIENT_SECRET:  ${env:KEY_7}
    BREATHE_TOKEN: ${env:KEY_4}

# public functions
functions:
  slack:
    handler: app.slack
    events:
      - http:
          path: slack/events
          method: post

# Offline development and .env file
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
