service: infobot-slack
frameworkVersion: '2'
useDotenv: true
# AWS
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-2
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_APP_TOKEN: ${env:SLACK_APP_TOKEN}
    SLACK_CLIENT_ID:  ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET:  ${env:SLACK_CLIENT_SECRET}
    BREATHE_TOKEN: ${env:BREATHE_TOKEN}
# public functions
functions:
  slack:
    handler: app.slack
    events:
      - http:
          path: slack/events
          method: post
  home:
    handler: app.home
    events:
      - http:
          path: /
          method: get
# Offline development and .env file
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
